# Generated by Django 3.2.7 on 2021-10-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_prreviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
    ]
